cyclomatic_complexity:
  ignores_case_statements: true
disabled_rules:
  - opening_brace # not compatible to SwiftFormat rule "wrapMultilineStatementBraces"
  - todo
excluded:
  - .build
  - .derivedData
  - DerivedData
  - Sources/Exporters/OpenTelemetryProtocolCommon/proto # generated
file_length:
  warning: 550
  ignore_comment_only_lines: true
force_cast: error
force_try: error
function_body_length: 80
function_parameter_count: 8
identifier_name:
  allowed_symbols: _
  max_length: 42
  excluded:
    - id
    - in
    - ok
    - to
    - x
    - y
    - z
large_tuple: 3
line_length:
  warning: 180
  error: 300
  ignores_comments: true
nesting:
  type_level:
    warning: 2
    error: 4
opt_in_rules:
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - force_cast
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_arguments
  - operator_usage_whitespace
  - overridden_super_call
type_body_length: 300
type_name:
  allowed_symbols: _
