name: Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test for macOS
      run: swift test --enable-code-coverage
    - name: Upload Code coverage
      run: |
        curl -Os https://uploader.codecov.io/latest/macos/codecov
        chmod +x codecov
        xcrun llvm-cov export -ignore-filename-regex="pb\.swift|grpc\.swift" -format="lcov" .build/debug/opentelemetry-swiftPackageTests.xctest/Contents/MacOS/opentelemetry-swiftPackageTests -instr-profile .build/debug/codecov/default.profdata > .build/debug/codecov/coverage_report.lcov
        ./codecov -f .build/debug/codecov/coverage_report.lcov
    - name: Install Homebrew kegs
      run: make setup_brew
    - name: Build for iOS
      run: make build_for_testing_ios
    - name: Test for iOS
      run: make test_without_building_ios
    - name: Build for watchOS
      run: make build_for_testing_watchos
    - name: Test for watchOS
      run: make test_without_building_watchos
